# LEGITIMATE BASE STATION - 5G NR Configuration

cu_cp:
  amf:
    addr: 127.0.0.5
    port: 38412
    bind_addr: 127.0.0.1
  supported_tracking_areas:
    - tac: 7
      plmn_list:
        - plmn: "00101"
          tai_slice_support_list:
            - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  clock: internal
  srate: 23.04
  otw_format: sc12
  tx_gain: 65
  rx_gain: 40

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone_config: 0
    prach_frequency_start: 0

log:
  filename: /tmp/legitimate_gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/legitimate_gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/legitimate_gnb_ngap.pcap

metrics:
  enable_json_metrics: true
  addr: 127.0.0.1
  port: 55555

