logger:
  file:
    path: /var/log/open5gs/mme.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

mme:
  freeDiameter: /etc/freeDiameter/mme.conf
  s1ap:
    server:
      - address: 127.0.1.2
  gtpc:
    server:
      - address: 127.0.0.2
    client:
      sgwc:
        - address: 127.0.0.3
      smf:
       - address: 127.0.0.4
  metrics:
    server:
      - address: 127.0.0.2
        port: 9090
  gummei:
    - plmn_id:
        mcc: 001
        mnc: 01
      mme_gid: 2
      mme_code: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 8
  security:
    integrity_order : [ EIA0 ]              # AUTHREJECT: ONLY null integrity (no protection)
    ciphering_order : [ EEA0 ]              # AUTHREJECT: ONLY null ciphering (no encryption)
    #
    # AUTHREJECT ATTACK: Authentication rejection is achieved by ensuring no valid
    # subscribers exist in the HSS database. When a UE with TAC 0x0008 attempts to
    # attach, the MME will reject it because the IMSI is not provisioned.
    #
    # To ensure rejection: sudo open5gs-dbctl remove <IMSI>
    # Or keep HSS database empty of subscribers for this attack network.
  network_name:
    full: AuthReject_Test
    short: AR_Test
  mme_name: open5gs-authreject-mme0
  time:
#    t3402:
#      value: 720   # 12 minutes * 60 = 720 seconds
#    t3412:
#      value: 3240  # 54 minutes * 60 = 3240 seconds
#    t3423:
#      value: 720   # 12 minutes * 60 = 720 seconds

################################################################################
# S1AP Server
################################################################################
#  o Listen on address available in `eth0` interface
#  ngap:
#    server:
#      - dev: eth0
#
################################################################################
# GTP-C Server
################################################################################
#  o Listen on IPv4 and IPv6
#  gtpc:
#    server:
#      - address: 127.0.0.2
#      - address: ::1
#
################################################################################
# GTP-C Client
################################################################################
#  o SGW selection by eNodeB TAC
#   (either single TAC or multiple TACs, DECIMAL representation)
#  gtpc:
#    client:
#      sgwc:
#        - address: 127.0.0.3
#          tac: 26000
#        - address: 127.0.2.2
#          tac: [25000, 27000, 28000]
#
#  o SGW selection by e_cell_id(28bit)
#   (either single or multiple e_cell_id, HEX representation)
#  gtpc:
#    client:
#      sgwc:
#        - address: 127.0.0.3
#          e_cell_id: abcde01
#        - address: 127.0.2.2
#          e_cell_id: [12345, a9413, 98765]
#
#  o SMF selection by APN
#  gtpc:
#    client:
#      smf:
#        - address: 127.0.0.4
#          apn: internet
#        - address: 127.0.0.5
#          apn: internet2
#        - address: 127.0.0.6
#          apn: ims
#        - address: 127.0.0.7
#          apn: voice

################################################################################
# GTP-U configuration
################################################################################
#  o GTP-U Server
#  gtpu:
#    server:
#      - address: 127.0.0.2
#      - address: ::1
#
################################################################################
# Metrics
################################################################################
#  o Metrics Server
#  metrics:
#    server:
#      - address: 127.0.0.2
#        port: 9090

################################################################################
# Parameter
################################################################################
#parameter:
#  no_ipv6: false
#  use_openair: false
#  verbosity_level: 0
#  config_interval: 1
#  shutdown: false

################################################################################
# Subscription Data
################################################################################
subscription:
  default:
    msisdn: 0000000000
    access_restriction_data: 32
    subscriber_status: 0
    network_access_mode: 0
    ambr:
      downlink: 1024000    # 1 Gbps
      uplink: 1024000      # 1 Gbps
    allocated_msisdn: 0000000000
    pdn:
      - apn: internet
        pdn_type: ipv4
        qos:
          qci: 9
          arp:
            priority_level: 8
            pre_emption_capability: 1
            pre_emption_vulnerability: 1
        ambr:
          downlink: 1024000    # 1 Gbps
          uplink: 1024000      # 1 Gbps
        pgw:
          - address: 127.0.0.3
        pco:
          - id: 1
            type: 1
            content: 00000c
          - id: 3
            type: 1
            content: 00000c
      - apn: ims
        pdn_type: ipv4v6
        qos:
          qci: 5
          arp:
            priority_level: 1
            pre_emption_capability: 0
            pre_emption_vulnerability: 0
        ambr:
          downlink: 1024000    # 1 Gbps
          uplink: 1024000      # 1 Gbps
        pgw:
          - address: 127.0.0.3
        pco:
          - id: 1
            type: 1
            content: 00000c
          - id: 3
            type: 1
            content: 00000c

################################################################################
# Handover Configuration
################################################################################
handover:
  s1:
    enable: true
  x2:
    enable: false
  inter_mme:
    enable: false

################################################################################
# Pool Configuration
################################################################################
#  o IPv4 Pool (not needed for DoS attack - UEs won't authenticate)
# pool:
#   ipv4: 127.0.1.0/24
#   ipv6: 2001:230:cafe::/48

################################################################################
# HSS Configuration
################################################################################
hss:
  freeDiameter: /etc/freeDiameter/hss.conf

################################################################################
# SGSN Configuration
################################################################################
#  o For 2G/3G Network
#  sgsn:
#    gtpc:
#      server:
#        - address: 127.0.0.2
#    gtpu:
#      server:
#        - address: 127.0.0.2
#    map:
#      mcc: 001
#      mnc: 01
#      code: 1

################################################################################
# SMF Configuration
################################################################################
#  o For 5G Network
#  smf:
#    gtpc:
#      server:
#        - address: 127.0.0.4
#    gtpu:
#      server:
#        - address: 127.0.0.4
#    pfcp:
#      server:
#        - address: 127.0.0.4
#    bsf:
#      server:
#        - address: 127.0.0.4
#    metrics:
#      server:
#        - address: 127.0.0.4
#        port: 9090
#    sbi:
#      server:
#        - address: 127.0.0.4
#        port: 7777
#    parameter:
#      no_ipv6: false
#      prefer_ipv4: true
#      verbosity_level: 0
#      config_interval: 1
#    session:
#      - subnet: 10.45.0.1/16
#      - subnet: 2001:230:cafe::1/48
#    pdn:
#      - apn: internet
#        pdn_type: ipv4
#        session:
#          - subnet: 10.45.0.1/16
#        pcc_rule:
#          - qos:
#              qci: 9
#              arp:
#                priority_level: 8
#                pre_emption_capability: 1
#                pre_emption_vulnerability: 1
#            flow:
#              - direction: downlink
#                description: allow out udp from any to 10.45.0.0/16
#              - direction: uplink
#                description: allow out udp from 10.45.0.0/16 to any
#              - direction: downlink
#                description: allow out tcp from any to 10.45.0.0/16
#              - direction: uplink
#                description: allow out tcp from 10.45.0.0/16 to any
#      - apn: ims
#        pdn_type: ipv4v6
#        session:
#          - subnet: 2001:230:cafe::1/48
#        pcc_rule:
#          - qos:
#              qci: 5
#              arp:
#                priority_level: 1
#                pre_emption_capability: 0
#                pre_emption_vulnerability: 0
#            flow:
#              - direction: downlink
#                description: allow out udp from any to 2001:230:cafe::/48
#              - direction: uplink
#                description: allow out udp from 2001:230:cafe::/48 to any
#              - direction: downlink
#                description: allow out tcp from any to 2001:230:cafe::/48
#              - direction: uplink
#                description: allow out tcp from 2001:230:cafe::/48 to any

################################################################################
# AMF Configuration
################################################################################
#  o For 5G Network
#  amf:
#    ngap:
#      server:
#        - address: 127.0.0.5
#    gtpc:
#      server:
#        - address: 127.0.0.5
#    sbi:
#      server:
#        - address: 127.0.0.5
#        port: 7777
#    metrics:
#      server:
#        - address: 127.0.0.5
#        port: 9090
#    guami:
#      - plmn_id:
#          mcc: 001
#          mnc: 01
#        amf_id:
#          region: 2
#          set: 1
#    tai:
#      - plmn_id:
#          mcc: 001
#          mnc: 01
#        tac: 1
#    plmn_support:
#      - plmn_id:
#          mcc: 001
#          mnc: 01
#        s_nssai:
#          - sst: 1
#    security:
#      integrity_order : [ NIA2, NIA1, NIA0 ]
#      ciphering_order : [ NEA0, NEA1, NEA2 ]
#    network_name:
#      full: Open5GS
#    amf_name: open5gs-amf0
#    parameter:
#      no_ipv6: false
#      verbosity_level: 0
#      config_interval: 1
